testing

diff --git a/modules/pcfconfig-pks b/modules/pcfconfig-pks
--- a/modules/pcfconfig-pks
+++ b/modules/pcfconfig-pks
@@ -2391,6 +2391,37 @@ echo "gcloud compute instances add-tags $vmnm --zone $zone --tags ${DNS_PREFIX}-
       fi
     fi
 
+    if [ "${PCF_CLOUD_NAME}" == "gcp" ]; then
+      vmnm=$(gcloud compute instances list --filter="labels.instance_group=( 'bosh' )" --format=json | jq -r '.[].name')
+      zone=$(gcloud compute instances list --filter="labels.instance_group=( 'bosh' )" --format=json | \
+             jq -r '.[].zone' | awk -F'/' '{ print $NF }')
+      messageTitle "Adding Network Tag (${DNS_PREFIX}-pks-api) for VM $vmnm"
+echo "gcloud compute instances add-tags $vmnm --zone $zone --tags ${DNS_PREFIX}-pks-api"
+      gcloud compute instances add-tags $vmnm --zone $zone --tags "${DNS_PREFIX}-pks-api" > /dev/null 2>&1
+      gcloud compute instances add-tags $vmnm --zone $zone --tags "pks-api" > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo "ERROR: failled to add network tag to VM $zone"
+        echo "       => gcloud compute instances add-tags $vmnm --zone $zone --tags 'pks-api'"
+        exit 1
+      fi
+
+      vmnm=$(gcloud compute instances list --filter="labels.job=( 'pivotal-container-service' )" --format=json | jq -r '.[].name')
+      zone=$(gcloud compute instances list --filter="labels.job=( 'pivotal-container-service' )" --format=json | \
+             jq -r '.[].zone' | awk -F'/' '{ print $NF }')
+
+      messageTitle "Adding Network Tag for PKS VM (${DNS_PREFIX}-pks-api) for VM $vmnm"
+echo "gcloud compute instances add-tags $vmnm --zone $zone --tags ${DNS_PREFIX}-pks-api"
+      gcloud compute instances add-tags $vmnm --zone $zone --tags "${DNS_PREFIX}-pks-api" > /dev/null 2>&1
+      gcloud compute instances add-tags $vmnm --zone $zone --tags "pks-api" > /dev/null 2>&1
+      if [ $? -ne 0 ]; then
+        echo "ERROR: failled to add network tag to VM $zone"
+        echo "       => gcloud compute instances add-tags $vmnm --zone $zone --tags 'pks-api'"
+        exit 1
+      fi
+    fi
+
+
+
     echo ""
     echo "Configuration of the PKS Tile is completed."
     exit 0
