test

diff --git a/modules/pcfconfig-pks-ingress b/modules/pcfconfig-pks-ingress
--- a/modules/pcfconfig-pks-ingress
+++ b/modules/pcfconfig-pks-ingress
@@ -135,6 +135,30 @@ if [ "${PCF_DEPLOYMENT_CLOUD}" == "AWS" ]; then
   fi
 fi
 
+if [ "${PCF_CLOUD_NAME}" == "GCP" ]; then
+echo "555555555555555555555555 - 1"
+  DNS_NAME="*.apps-${cluster}"
+  echo "Create DNS Entry for *.apps-${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}:"
+
+  cnt=$(gcloud dns record-sets list -z ${DNS_PREFIX}-zone --name "${DNS_NAME}." \
+          --type=A 2> /dev/null | wc -l | sed 's/ //g')
+  if [ ${cnt} -eq 0 ]; then
+    messagePrint " - Creating DNS Entry in (${DNS_PREFIX}-zone)" "${DNS_NAME}"
+    ipa=$(gcloud compute forwarding-rules describe ${DNS_PREFIX}-$cluster --region=$GCP_REGION | \
+        grep IPAddress | awk '{ print $NF }')
+    gcloud dns record-sets transaction start -z ${DNS_PREFIX}-zone > /dev/null 2>&1
+    gcloud dns record-sets transaction add "$ipa" --name ${DNS_NAME}. \
+       --type A -z ${DNS_PREFIX}-zone --ttl=300 > /dev/null 2>&1
+    gcloud dns record-sets transaction execute -z ${DNS_PREFIX}-zone > /dev/null 2>&1; ret=$?
+    if [ ${ret} -ne 0 ]; then
+      echo "ERROR: Creating DNS record-sets for zone (${DNS_PREFIX}-zone)"
+      exit 1
+    fi
+  fi
+echo "555555555555555555555555 - 10"
+fi
+
+
 if [ "${PCF_DEPLOYMENT_CLOUD}" == "Azure" ]; then
   DNS_NAME="*.apps-${cluster}"
   echo "Create DNS Entry for *.apps.${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}:"
@@ -168,7 +192,6 @@ if [ "${PCF_DEPLOYMENT_CLOUD}" == "Azure" ]; then
 fi
 
 if [ "${AWS_HOSTED_ZONE_ID}" != "" -a "${PCF_DEPLOYMENT_CLOUD}" == "AWS" ]; then
-
   ZONE_ID_STR=$(echo "${ZONE_ID}" | awk -F'/' '{ print $NF }')
   DNSLB=$(aws elb --region $AWS_REGION describe-load-balancers --load-balancer-names "$AWS_ID" | \
       jq -r '.LoadBalancerDescriptions[0].DNSName')
