ingress tesing

diff --git a/modules/pcfconfig-pks-ingress b/modules/pcfconfig-pks-ingress
--- a/modules/pcfconfig-pks-ingress
+++ b/modules/pcfconfig-pks-ingress
@@ -59,10 +59,9 @@ kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-adm
         --serviceaccount=kube-system:default > /dev/null 2>&1
 cnt=$(kubectl get namespace | egrep -c "^ingress ")
 if [ $cnt -eq 0 ]; then
-  messageTitle "Install Ingress Routing on ($cluster)"
-  messagePrint " - Namespace:"                  "ingress"
-  messagePrint " - Ingress Release:"            "stable/nginx-ingress"
-  messagePrint " - Options:"                    "controller.config.proxy-buffer-size=16k"
+  messageTitle "Install and configure Helm Charts"
+  messagePrint " - Helm Version:"         "$(helm version --short)"
+  messagePrint " - Helm Repo:"            "https://kubernetes-charts.storage.googleapis.com"
 
   HELM=$(which helm)
   if [ ! -x "$HELM" ]; then
@@ -71,25 +70,35 @@ if [ $cnt -eq 0 ]; then
   fi
 
   # --- INSTALLING HELM ---
-  helm init --history-max 200 > /dev/null 2>&1
+  helm repo add stable https://kubernetes-charts.storage.googleapis.com/ > /dev/null 2>&1
   helm repo update > /dev/null 2>&1
   kubectl apply -f $PCFCONFIG_PATH/demos/k8s-helm/rbac-config.yaml > /dev/null 2>&1
   helm init --service-account tiller > /dev/null 2>&1
   sleep 30
-  helm install stable/nginx-ingress \
-    --namespace ingress \
-    --set rbac.create=true \
-    --set name=ingress \
-    --set controller.config.proxy-buffer-size=16k
-    #--set controller.config.proxy-buffer-size=16k > /dev/null 2>&1
-  if [ $? -ne 0 ]; then
-    echo "ERROR: failed to deploy ingress controller with helm"
-    echo "       => helm install stable/nginx-ingress --name nginx --set rbac.create=true \\"
-    echo "          --namespace ingress --set controller.config.proxy-buffer-size=16k"
-    echo ""
-    debugInfos $(($BITMASK_JMP+$BITMASK_OPS+$BITMASK_PXS+$BITMASK_K8S))
 
-    exit 1
+  messageTitle "Install Ingress Routing on ($cluster)"
+  messagePrint " - Namespace:"                  "ingress"
+  messagePrint " - Ingress Release:"            "stable/nginx-ingress"
+  messagePrint " - Options:"                    "controller.config.proxy-buffer-size=16k"
+
+  # --- VERIFY NAMESPACE ---
+  kubectl get namespace ingress > /dev/null 2>&1
+  if [ $? -eq 0 ]; then
+    kubectl create namespace ingress > /dev/null 2>&1
+  fi
+
+  cnt=$(helm list --namespace ingress --filter nginx-ingress-cl1 -q) 
+  if [ "${cnt}" == "" ]; then
+    helm install nginx-ingress-cl1 stable/nginx-ingress --set rbac.create=true --namespace ingress
+    if [ $? -ne 0 ]; then
+      echo "ERROR: failed to deploy ingress controller with helm"
+      echo "       => helm install stable/nginx-ingress --name nginx --set rbac.create=true \\"
+      echo "          --namespace ingress --set controller.config.proxy-buffer-size=16k"
+      echo ""
+      debugInfos $(($BITMASK_JMP+$BITMASK_OPS+$BITMASK_PXS+$BITMASK_K8S))
+  
+      exit 1
+    fi
   fi
 fi
 
