testing

diff --git a/modules/pcfconfig-pks-harbor b/modules/pcfconfig-pks-harbor
--- a/modules/pcfconfig-pks-harbor
+++ b/modules/pcfconfig-pks-harbor
@@ -55,7 +55,7 @@ TLS_PRIVATE_KEY=$PCFPATH/certificates/privkey.pem
 TLS_ROOT_CERT=$PCFPATH/certificates/ca.pem
 VARFILE=/tmp/harbor_vars.yml; rm -rf $VARFILE; touch $VARFILE
 
-if [ -f "${TLS_CERTIFICATE}" -a -f "${TLS_PRIVATE_KEY}" == "" -a -f "${TLS_ROOT_CERT}" ]; then
+if [ -f "${TLS_CERTIFICATE}" -a -f "${TLS_PRIVATE_KEY}" -a -f "${TLS_ROOT_CERT}" ]; then
   TLS_HOST_NAME=harbor.${PCF_DEPLOYMENT_ENV_NAME}.${AWS_HOSTED_DNS_DOMAIN}
   messagePrint " - Verify Customer TLS Certificate for hosts" "${TLS_HOST_NAME}"
   verifyTLScertificate $TLS_CERTIFICATE $TLS_PRIVATE_KEY
@@ -67,6 +67,24 @@ if [ -f "${TLS_CERTIFICATE}" -a -f "${TLS_PRIVATE_KEY}" == "" -a -f "${TLS_ROOT_
   echo "container_service_pks_tls_cert_pem: \"$TLS_CERTIFICATE_STRING\"" >> $VARFILE
   echo "container_service_pks_tls_private_key_pem: \"$TLS_PRIVATE_KEY_STRING\"" >> $VARFILE
   echo "container_service_pks_tls_root_cert_pem: \"$TLS_ROOT_CERT_STRING\"" >> $VARFILE
+else
+  TLS_HOST_NAME=harbor.${PCF_DEPLOYMENT_ENV_NAME}.${AWS_HOSTED_DNS_DOMAIN}
+  messagePrint " - Generating Customer TLS Certificate" "${TLS_HOST_NAME}"
+
+  TLS_TEMP_CERT=/tmp/$$_cert
+  $OM $OM_LOGIN generate-certificate --domains $TLS_HOST_NAME > $TLS_TEMP_CERT
+  if [ $? -ne 0 ]; then
+    echo "ERROR: Generating Certificate for $TLS_HOST_NAME failed"; exit 1
+  fi
+
+  TLS_CERTIFICATE=$(jq '.certificate' $TLS_TEMP_CERT)
+  TLS_PRIVATE_KEY=$(jq '.key' $TLS_TEMP_CERT)
+
+  echo "container_service_pks_tls_cert_pem: $TLS_CERTIFICATE" >> $VARFILE
+  echo "container_service_pks_tls_private_key_pem: $TLS_PRIVATE_KEY" >> $VARFILE
+  echo "container_service_pks_tls_root_cert_pem: " >> $VARFILE
+
+  rm -f $TLS_TEMP_CERT
 fi
 
 ##############################################################################################
