repeat file download if failed up to 3 time

diff --git a/modules/pcfconfig-terraform b/modules/pcfconfig-terraform
--- a/modules/pcfconfig-terraform
+++ b/modules/pcfconfig-terraform
@@ -1739,15 +1739,20 @@ if [ "${PCFCONFIG_BASE}" == "pcfconfig-pks" -o "${PCFCONFIG_BASE}" == "pcfconfig
         exit 1
       fi
 
+      i=1
+      while [ $i -le 3 ]; then 
+        echo "-----------------------------------------------------------------------------------------------------------"
+        ssh -qi $TMP_OPSMAN ubuntu@${OPS_MANAGER_DNS} -n "sudo /tmp/om-install.sh"; ret=$?
+
+        if [ ${ret} -ne 0 -a $i -eq 3 ]; then
+          echo "ERROR: executing remote-script: /tmp/om-install.sh on ubuntu@${OPS_MANAGER_DNS} has been failed"
+          echo "       Please try manually:"
+          echo "       => ssh -i $TMP_OPSMAN ubuntu@${OPS_MANAGER_DNS} -n \"sudo /tmp/om-install.sh\""
+          exit 1
+        fi
+        let i=i+1
+      done
       echo "-----------------------------------------------------------------------------------------------------------"
-      ssh -qi $TMP_OPSMAN ubuntu@${OPS_MANAGER_DNS} -n "sudo /tmp/om-install.sh"; ret=$?
-      echo "-----------------------------------------------------------------------------------------------------------"
-      if [ ${ret} -ne 0 ]; then
-        echo "ERROR: executing remote-script: /tmp/om-install.sh on ubuntu@${OPS_MANAGER_DNS} has been failed"
-        echo "       Please try manually:"
-        echo "       => ssh -i $TMP_OPSMAN ubuntu@${OPS_MANAGER_DNS} -n \"sudo /tmp/om-install.sh\""
-        exit 1
-      fi
     fi
   fi
 
