ingress tesing

diff --git a/modules/pcfconfig-pks-ingress b/modules/pcfconfig-pks-ingress
--- a/modules/pcfconfig-pks-ingress
+++ b/modules/pcfconfig-pks-ingress
@@ -35,12 +35,20 @@ API_HOST_NAME=api.pks.${PCF_DEPLOYMENT_ENV_NAME}.${AWS_HOSTED_DNS_DOMAIN}
   echo ""
 
 # --- LOGIN TO PKS ---
-i=1
+i=1; stt=1
 while [ $i -lt 10 ]; do
   pks login -u ${PKS_ADMIN_USER} -p ${PKS_ADMIN_PASS} -a ${API_HOST_NAME} --skip-ssl-validation > /dev/null 2>&1
-  if [ $? -eq 0 ]; then break; fi
+  if [ $? -eq 0 ]; then break; stt=0; fi
   let i=i+1; sleep 10
 done
+
+if [ $stt -eq 1 ]; then
+  debugInfos $(($BITMASK_JMP+$BITMASK_OPS+$BITMASK_PKS))
+
+  echo "ERROR: Failed to login to pks"
+  echo " 
+
+fi
 
 
 exit 1
