testing

diff --git a/modules/pcfconfig-pks-harbor b/modules/pcfconfig-pks-harbor
--- a/modules/pcfconfig-pks-harbor
+++ b/modules/pcfconfig-pks-harbor
@@ -413,6 +413,23 @@ echo "MST:$mst"
 ############################## ADD HARBOR NODES TO BACKEND-POOL ##############################
 ##############################################################################################
 
+xxxxxxxxx
+if [ "${PCF_DEPLOYMENT_CLOUD}" == "AWS" ]; then
+  aws elb --region $AWS_REGION describe-load-balancers --load-balancer-names "${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb" > /dev/null 2>&1; ret=$?
+  if [ ${ret} -eq 0 ]; then
+    for ins in $mst; do
+      aws elb --region $AWS_REGION register-instances-with-load-balancer \
+         --load-balancer-name ${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb --instances "${ins}" > /dev/null 2>&1; ret=$?
+      if [ ${ret} -ne 0 ]; then
+        echo "ERROR: Register Instances"
+        echo "aws elb --region $AWS_REGION register-instances-with-load-balancer \\"
+        echo "  --load-balancer-name ${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb --instances $ins"
+        exit 1
+      fi
+    done
+  fi
+fi
+
 if [ "${PCF_DEPLOYMENT_CLOUD}" == "Azure" ]; then
   messagePrint "Adding Master Nodes of PKS Cluster ($n) to LB" "${n}-lb"
   for node in $mst; do
