debug terraform error

diff --git a/modules/pcfconfig-terraform b/modules/pcfconfig-terraform
--- a/modules/pcfconfig-terraform
+++ b/modules/pcfconfig-terraform
@@ -558,63 +558,64 @@ checkEnvironment() {
 
         wait_loop 60 "Waiting for DNS records to be pushed"
 
-      # --- GCP CHEKING DNS ---
-      echo "Validating GCP OPS Manager DNS records ($OPS_MANAGER_DNS)"
-      nslookup -timeout=10 $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
-      if [ $ret -ne 0 ]; then 
+        # --- GCP CHEKING DNS ---
+        echo "Validating GCP OPS Manager DNS records ($OPS_MANAGER_DNS)"
+        nslookup -timeout=10 $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
+        if [ $ret -ne 0 ]; then 
+          i=1; ret="failed"; dns_google_stat="failed"
+           while [ $i -lt 10 -a ${ret} == "failed" ]; do
+            sleep 10
+            nslookup $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
+            if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
+            messagePrint "   => Verify DNS lookup Google (8.8.8.8)" "$dns_google_stat"
+            let i=i+1
+          done
+        else
+          messagePrint "   => Verify DNS lookup Google (8.8.8.8)" "successful"
+        fi
+
+        for n in $DNS_SERVERS; do
+          nslookup $OPS_MANAGER_DNS $n > /dev/null 2>&1; ret=$?
+          if [ $ret -eq 0 ]; then dns_stat="successful"; else dns_stat="failed"; fi
+          messagePrint "   => Verify DNS lookup ($n)" "$dns_stat"
+        done
+
+        localdns=$(nslookup localhost | grep Server:  | awk '{ print $2 }')
         i=1; ret="failed"; dns_google_stat="failed"
-         while [ $i -lt 10 -a ${ret} == "failed" ]; do
+         while [ $i -lt 30 -a ${ret} == "failed" ]; do
           sleep 10
-          nslookup $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
+          nslookup $OPS_MANAGER_DNS > /dev/null 2>&1; ret=$?
           if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
-          messagePrint "   => Verify DNS lookup Google (8.8.8.8)" "$dns_google_stat"
+          messagePrint "   => Verify DNS lookup localhost ($localdns)" "$dns_google_stat"
           let i=i+1
         done
-      else
-        messagePrint "   => Verify DNS lookup Google (8.8.8.8)" "successful"
-      fi
 
-      for n in $DNS_SERVERS; do
-        nslookup $OPS_MANAGER_DNS $n > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_stat="successful"; else dns_stat="failed"; fi
-        messagePrint "   => Verify DNS lookup ($n)" "$dns_stat"
-      done
+        messagePrint " - Ops Manager Public IP" "$OPS_MANAGER_PUBLIC_IP"
+        messagePrint " - Ops Manager Private IP" "$OPS_MANAGER_PRIVATE_IP"
 
-      localdns=$(nslookup localhost | grep Server:  | awk '{ print $2 }')
-      i=1; ret="failed"; dns_google_stat="failed"
-       while [ $i -lt 30 -a ${ret} == "failed" ]; do
-        sleep 10
-        nslookup $OPS_MANAGER_DNS > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
-        messagePrint "   => Verify DNS lookup localhost ($localdns)" "$dns_google_stat"
-        let i=i+1
-      done
+#hullu
+        if [ "${dns_google_stat}" == "failed" ]; then
+          messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_stat"
+          subdomain=$(echo $OPS_MANAGER_DNS | sed -e 's/\./<1>/' -e 's/^.*<1>//g')
+          sublen=$(echo $subdomain | wc -c | sed 's/ *//g')
 
-      messagePrint " - Ops Manager Public IP" "$OPS_MANAGER_PUBLIC_IP"
-      messagePrint " - Ops Manager Private IP" "$OPS_MANAGER_PRIVATE_IP"
+          echo ""
+          echo "ERROR: DNS entry for $OPS_MANAGER_DNS external to AWS seams not to be working."
+          echo "       Make sure you add a NS entry for your subdomain $subdomain on your DNS zone"
+          echo "       for $AWS_DNS_SUFFIX."
+          echo ""
+          printf "      %${sublen}s    NS     $DNS1\n" "$subdomain"
+          printf "      %${sublen}s           $DNS2\n" ""
+          printf "      %${sublen}s           $DNS3\n" ""
+          printf "      %${sublen}s           $DNS4\n" ""
 
-      if [ "${dns_google_stat}" == "failed" ]; then
-        messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_stat"
-        subdomain=$(echo $OPS_MANAGER_DNS | sed -e 's/\./<1>/' -e 's/^.*<1>//g')
-        sublen=$(echo $subdomain | wc -c | sed 's/ *//g')
+          echo ""
 
-        echo ""
-        echo "ERROR: DNS entry for $OPS_MANAGER_DNS external to AWS seams not to be working."
-        echo "       Make sure you add a NS entry for your subdomain $subdomain on your DNS zone"
-        echo "       for $AWS_DNS_SUFFIX."
-        echo ""
-        printf "      %${sublen}s    NS     $DNS1\n" "$subdomain"
-        printf "      %${sublen}s           $DNS2\n" ""
-        printf "      %${sublen}s           $DNS3\n" ""
-        printf "      %${sublen}s           $DNS4\n" ""
-
-        echo ""
-
-        echo "OpsManager Name can not be resolved through DNS"
-        exit 1
-      else
-        OPS_MANAGER=OPS_MANAGER_DNS
-      fi
+          echo "3OpsManager Name can not be resolved through DNS"
+          exit 1
+        else
+          OPS_MANAGER=OPS_MANAGER_DNS
+        fi
       fi
     fi
 
@@ -763,71 +764,60 @@ echo "xxxx aws route53 change-resource-record-sets --hosted-zone-id $ROUTE53_TOK
           echo "         please try manually"
         fi
 
-exit 1
-
         wait_loop 60 "Waiting for DNS records to be pushed"
 
-      # --- AWS CHEKING DNS ---
-      echo "Validating OPS Manager DNS records ($OPS_MANAGER_DNS)"
-      i=1; ret="failed"; dns_google_stat="failed"
-       while [ $i -lt 10 -a ${ret} == "failed" ]; do
-        sleep 10
-        nslookup $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
-        messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_google_stat"
-        let i=i+1
-      done
-
-      for n in $DNS_SERVERS; do
-        nslookup $OPS_MANAGER_DNS $n > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_stat="successful"; else dns_stat="failed"; fi
-        messagePrint "   => Verify DNS lookup ($n)" "$dns_stat"
-      done
-
-      localdns=$(nslookup localhost | grep Server:  | awk '{ print $2 }')
-      i=1; ret="failed"; dns_google_stat="failed"
-       while [ $i -lt 30 -a ${ret} == "failed" ]; do
-        sleep 10
-        nslookup $OPS_MANAGER_DNS > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
-        messagePrint "   => Verify DNS lookup localhost ($localdns)" "$dns_google_stat"
-        let i=i+1
-      done
-
-      messagePrint " - Ops Manager Public IP" "$OPS_MANAGER_PUBLIC_IP"
-      messagePrint " - Ops Manager Private IP" "$OPS_MANAGER_PRIVATE_IP"
-
-      if [ "${dns_google_stat}" == "failed" ]; then
-        messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_stat"
-        subdomain=$(echo $OPS_MANAGER_DNS | sed -e 's/\./<1>/' -e 's/^.*<1>//g')
-        sublen=$(echo $subdomain | wc -c | sed 's/ *//g')
-
-        echo ""
-        echo "ERROR: DNS entry for $OPS_MANAGER_DNS external to AWS seams not to be working."
-        echo "       Make sure you add a NS entry for your subdomain $subdomain on your DNS zone"
-        echo "       for $AWS_DNS_SUFFIX."
-        echo ""
-        printf "      %${sublen}s    NS     $DNS1\n" "$subdomain"
-        printf "      %${sublen}s           $DNS2\n" ""
-        printf "      %${sublen}s           $DNS3\n" ""
-        printf "      %${sublen}s           $DNS4\n" ""
-
-        echo ""
-
-        echo "OpsManager Name can not be resolved through DNS"
-        while [ 1 ]; do
-          echo -e "Do you want to configure the OpsManager with its ip-address $OPS_MANAGER_PUBLIC_IP instead <y/n>: \c"; read x
-          if [ "$x" == "y" -o "$x" == "n" ]; then break; fi
+        # --- AWS CHEKING DNS ---
+        echo "Validating OPS Manager DNS records ($OPS_MANAGER_DNS)"
+        i=1; ret="failed"; dns_google_stat="failed"
+         while [ $i -lt 10 -a ${ret} == "failed" ]; do
+          sleep 10
+          nslookup $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
+          if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
+          messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_google_stat"
+          let i=i+1
         done
 
-        if [ $x == "y" ]; then
-          OPS_MANAGER=$OPS_MANAGER_PUBLIC_IP
+        for n in $DNS_SERVERS; do
+          nslookup $OPS_MANAGER_DNS $n > /dev/null 2>&1; ret=$?
+          if [ $ret -eq 0 ]; then dns_stat="successful"; else dns_stat="failed"; fi
+          messagePrint "   => Verify DNS lookup ($n)" "$dns_stat"
+        done
+
+        localdns=$(nslookup localhost | grep Server:  | awk '{ print $2 }')
+        i=1; ret="failed"; dns_google_stat="failed"
+         while [ $i -lt 30 -a ${ret} == "failed" ]; do
+          sleep 10
+          nslookup $OPS_MANAGER_DNS > /dev/null 2>&1; ret=$?
+          if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
+          messagePrint "   => Verify DNS lookup localhost ($localdns)" "$dns_google_stat"
+          let i=i+1
+        done
+
+        messagePrint " - Ops Manager Public IP" "$OPS_MANAGER_PUBLIC_IP"
+        messagePrint " - Ops Manager Private IP" "$OPS_MANAGER_PRIVATE_IP"
+
+        if [ "${dns_google_stat}" == "failed" ]; then
+          messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_stat"
+          subdomain=$(echo $OPS_MANAGER_DNS | sed -e 's/\./<1>/' -e 's/^.*<1>//g')
+          sublen=$(echo $subdomain | wc -c | sed 's/ *//g')
+
+          echo ""
+          echo "ERROR: DNS entry for $OPS_MANAGER_DNS external to AWS seams not to be working."
+          echo "       Make sure you add a NS entry for your subdomain $subdomain on your DNS zone"
+          echo "       for $AWS_DNS_SUFFIX."
+          echo ""
+          printf "      %${sublen}s    NS     $DNS1\n" "$subdomain"
+          printf "      %${sublen}s           $DNS2\n" ""
+          printf "      %${sublen}s           $DNS3\n" ""
+          printf "      %${sublen}s           $DNS4\n" ""
+
+          echo ""
+
+          echo "2OpsManager Name can not be resolved through DNS"
+          exit 1
         else
-          echo "$0 - Programm Ended"; exit 1
+          OPS_MANAGER=OPS_MANAGER_DNS
         fi
-      else
-        OPS_MANAGER=OPS_MANAGER_DNS
-      fi
       fi
 
 #NOT WORKING WITH TWO VM's NOE 'running' and one 'rerminated'
@@ -977,57 +967,48 @@ exit 1
 
         wait_loop 60 "Waiting for DNS records to be pushed"
 
-      # --- AZURE CHEKING DNS ---
-      echo "Validating OPS Manager DNS records ($OPS_MANAGER_DNS)"
-      i=1; ret="failed"
-       while [ $i -lt 10 -a ${ret} == "failed" ]; do
-        sleep 10
-        nslookup $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
-        messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_google_stat"
-        let i=i+1
-      done
-
-      for n in $DNS_SERVERS; do
-        nslookup $OPS_MANAGER_DNS $n > /dev/null 2>&1; ret=$?
-        if [ $ret -eq 0 ]; then dns_stat="successful"; else dns_stat="failed"; fi
-        messagePrint "   => Verify DNS lookup ($n)" "$dns_stat"
-      done
-
-      messagePrint " - Ops Manager Public IP" "$OPS_MANAGER_PUBLIC_IP"
-      messagePrint " - Ops Manager Private IP" "$OPS_MANAGER_PRIVATE_IP"
-
-      if [ "$dns_google_stat" == "failed" ]; then
-        messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_stat"
-        subdomain=$(echo $OPS_MANAGER_DNS | sed -e 's/\./<1>/' -e 's/^.*<1>//g')
-        sublen=$(echo $subdomain | wc -c | sed 's/ *//g')
-
-        echo ""
-        echo "ERROR: DNS entry for $OPS_MANAGER_DNS external to AWS seams not to be working."
-        echo "       Make sure you add a NS entry for your subdomain $subdomain on your DNS zone"
-        echo "       for $AWS_DNS_SUFFIX."
-        echo ""
-        printf "      %${sublen}s    NS     $DNS1\n" "$subdomain"
-        printf "      %${sublen}s           $DNS2\n" ""
-        printf "      %${sublen}s           $DNS3\n" ""
-        printf "      %${sublen}s           $DNS4\n" ""
-
-        echo ""
-
-        echo "OpsManager Name can not be resolved through DNS"
-        while [ 1 ]; do
-          echo -e "Do you want to configure the OpsManager with its ip-address $OPS_MANAGER_PUBLIC_IP instead <y/n>: \c"; read x
-          if [ "$x" == "y" -o "$x" == "n" ]; then break; fi
+        # --- AZURE CHEKING DNS ---
+        echo "Validating OPS Manager DNS records ($OPS_MANAGER_DNS)"
+        i=1; ret="failed"
+         while [ $i -lt 10 -a ${ret} == "failed" ]; do
+          sleep 10
+          nslookup $OPS_MANAGER_DNS 8.8.8.8 > /dev/null 2>&1; ret=$?
+          if [ $ret -eq 0 ]; then dns_google_stat="successful"; fi
+          messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_google_stat"
+          let i=i+1
         done
 
-        if [ $x == "y" ]; then
-          OPS_MANAGER=$OPS_MANAGER_PUBLIC_IP
+        for n in $DNS_SERVERS; do
+          nslookup $OPS_MANAGER_DNS $n > /dev/null 2>&1; ret=$?
+          if [ $ret -eq 0 ]; then dns_stat="successful"; else dns_stat="failed"; fi
+          messagePrint "   => Verify DNS lookup ($n)" "$dns_stat"
+        done
+
+        messagePrint " - Ops Manager Public IP" "$OPS_MANAGER_PUBLIC_IP"
+        messagePrint " - Ops Manager Private IP" "$OPS_MANAGER_PRIVATE_IP"
+
+        if [ "$dns_google_stat" == "failed" ]; then
+          messagePrint "   Verify DNS lookup Google (8.8.8.8)" "$dns_stat"
+          subdomain=$(echo $OPS_MANAGER_DNS | sed -e 's/\./<1>/' -e 's/^.*<1>//g')
+          sublen=$(echo $subdomain | wc -c | sed 's/ *//g')
+
+          echo ""
+          echo "ERROR: DNS entry for $OPS_MANAGER_DNS external to AWS seams not to be working."
+          echo "       Make sure you add a NS entry for your subdomain $subdomain on your DNS zone"
+          echo "       for $AWS_DNS_SUFFIX."
+          echo ""
+          printf "      %${sublen}s    NS     $DNS1\n" "$subdomain"
+          printf "      %${sublen}s           $DNS2\n" ""
+          printf "      %${sublen}s           $DNS3\n" ""
+          printf "      %${sublen}s           $DNS4\n" ""
+
+          echo ""
+
+          echo "1OpsManager Name can not be resolved through DNS"
+          exit 1
         else
-          echo "$0 - Programm Ended"; exit 1
+          OPS_MANAGER=OPS_MANAGER_DNS
         fi
-      else
-        OPS_MANAGER=OPS_MANAGER_DNS
-      fi
       fi
     fi
   else
