test

diff --git a/modules/pcfconfig-pas b/modules/pcfconfig-pas
--- a/modules/pcfconfig-pas
+++ b/modules/pcfconfig-pas
@@ -3480,11 +3480,23 @@ echo "DNSLB:$DNSLB gaga"
           echo "    \"AliasTarget\": {"                              >> $TMPROUTE53
           echo "      \"HostedZoneId\": \"${DNSLB_ZONEID}\","        >> $TMPROUTE53
           echo "      \"DNSName\": \"dualstack.${DNSLB}.\","         >> $TMPROUTE53
-          echo "      \"EvaluateTargetHealth\": \"${true}\","        >> $TMPROUTE53
+          echo "      \"EvaluateTargetHealth\": \"true\","           >> $TMPROUTE53
           echo "    }"                                               >> $TMPROUTE53
           echo "}}]"                                                 >> $TMPROUTE53
           echo "}"                                                   >> $TMPROUTE53
 
+          aws route53 change-resource-record-sets --hosted-zone-id $ZONE_ID \
+              --change-batch file://${TMPROUTE53} > /dev/null 2>&1
+          if [ $? -ne 0 ]; then
+            echo "ERROR: failed to set DNS for $hnm"
+            echo "       => aws route53 change-resource-record-sets --hosted-zone-id \"${ZONE_ID}\" \\"
+            echo "              --change-batch file://${TMPROUTE53}"
+            cat $TMPROUTE53
+            exit 1
+          fi
+
+echo gaga
+sleep 10000
 
 cat $TMPROUTE53
 
