Azure PKS 1.6 / Opsman 2.7 and Harbor 1.9

diff --git a/modules/pcfconfig-pks-harbor b/modules/pcfconfig-pks-harbor
--- a/modules/pcfconfig-pks-harbor
+++ b/modules/pcfconfig-pks-harbor
@@ -61,7 +61,6 @@ AVAILABILITY_ZONES=$(aws ec2 --region=$AWS_REGION describe-availability-zones | 
 AVAILABILITY_ZONE1=$(echo "${AVAILABILITY_ZONES}" | awk '{ print $1 }')
 AVAILABILITY_ZONE2=$(echo "${AVAILABILITY_ZONES}" | awk '{ print $2 }')
 AVAILABILITY_ZONE3=$(echo "${AVAILABILITY_ZONES}" | awk '{ print $3 }')
-echo "AVAILABILITY_ZONE1:$AVAILABILITY_ZONE1"
 
 messageTitle "Configuring Harbor Tile (${PCF_TILE_HARBOR_CONFIG})"
 messagePrint " - Harbor YAML Configuration Template" "\$PCFCONFIG_PATH/templates/${PCF_TILE_HARBOR_CONFIG}"
@@ -135,7 +134,44 @@ fi
 ##############################################################################################
 ################################ CONFIGURE PKS LOADBALANCERS #################################
 ##############################################################################################
-messageTitle "Creating Workload LoadBalancer (${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb)"
+messageTitle "Creating Harbor LoadBalancer (${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb)"
+
+if [ "${PCF_DEPLOYMENT_CLOUD}" == "Azure" ]; then
+  ERRAFORM_VARS=terraform.tfvars
+  TERRAFORM_TFSTATE=terraform.tfstate
+
+echo "$PWD"
+pwd
+
+  # --- CREATE ELB LOADBALANCER ---
+  SUB1=$($JQ -r '.modules[].outputs.public_subnet_ids.value[0]' $TERRAFORM_TFSTATE | grep -v null | sed '/: $/d' | sort -u)
+  SUB2=$($JQ -r '.modules[].outputs.public_subnet_ids.value[1]' $TERRAFORM_TFSTATE | grep -v null | sed '/: $/d' | sort -u)
+  SUB3=$($JQ -r '.modules[].outputs.public_subnet_ids.value[2]' $TERRAFORM_TFSTATE | grep -v null | sed '/: $/d' | sort -u)
+  SECG=$($JQ -r '.modules[].resources."aws_security_group.pks_api_lb_security_group".primary.id' $TERRAFORM_TFSTATE | \
+     grep -v null | sed '/: $/d' | sort -u)
+
+  messagePrint " - Subnet-1:" "$SUB1"
+  messagePrint " - Subnet-2:" "$SUB2"
+  messagePrint " - Subnet-3:" "$SUB3"
+  messagePrint " - Security Group:" "$SECG"
+
+#  aws elb --region $AWS_REGION describe-load-balancers \
+#          --load-balancer-names "${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb" > /dev/null 2>&1; ret=$?
+#  if [ ${ret} -gt 0 ]; then
+#    aws elb create-load-balancer --region $AWS_REGION  --load-balancer-name "${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb" \
+#       --tags "Key=Environment,Value=$AWS_DNS_PREFIX" \
+#       --listeners "Protocol=TCP,LoadBalancerPort=443,InstanceProtocol=TCP,InstancePort=443" \
+#       --subnet $SUB1 $SUB2 $SUB3 --security-groups $SECG > /dev/null 2>&1; ret=$?
+#    if [ ${ret} -ne 0 ]; then
+#      echo "ERROR: Creating LoadBalancer"
+#      echo "aws elb create-load-balancer --region $AWS_REGION  --load-balancer-name \"${PCF_DEPLOYMENT_ENV_NAME}-harbor-lb\" \\"
+#      echo "  --tags \"Key=Environment,Value=$AWS_DNS_PREFIX\" \\"
+#      echo "  --listeners \"Protocol=TCP,LoadBalancerPort=443,InstanceProtocol=TCP,InstancePort=443\" \\"
+#      echo "  --subnet $SUB1 $SUB2 $SUB3 --security-groups $SECG"
+#      exit 1
+#    fi
+
+fi 
 
 if [ "${PCF_DEPLOYMENT_CLOUD}" == "Azure" ]; then
   # --- CREATE PULIC IP FOR LOADBALANCER ---
