deployPCF added

diff --git a/deployPCF b/deployPCF
--- a/deployPCF
+++ b/deployPCF
@@ -1,13 +1,16 @@
 #!/bin/bash
 # ############################################################################################
-# File: ........: deployPAS.sh
+# File: ........: deployPCF.sh
 # Language .....: bash
 # Author .......: Sacha Dubois, Pivotal
 # Description ..: PCF Installation and Configuration Utility
 # ############################################################################################
 
-PCFDEPLOY=$(basename $0)
-PCFPATH=$(dirname $0)
+export PCFDEPLOY=$(basename $0)
+export PCFPATH=$(dirname $0)
+if [ "$PCFPATH" == "." ]; then 
+  export PCFPATH=$(pwd)
+fi
 
 . $PCFPATH/functions
 
@@ -63,7 +66,18 @@ if [ $cnt -eq 0 ]; then
   echo "ERROR: $pcf_deployment is not a correct PCFCONFIG deployment configuration file"
   exit 1
 else
+  missing_variables=0
+
   .  ${PCFPATH}/deployments/${DEPLOYMENT}
+  if [ $? -ne 0 ]; then 
+    echo "ERROR: in ${PCFPATH}/deployments/${DEPLOYMENT}"
+    exit 1
+  fi
+
+  # --- CHECK ENVIRONMENT VARIABLES ---
+  if [ -f ~/.pcfconfig ]; then 
+    . ~/.pcfconfig
+  fi
 
   echo "Deployment Settings"
   messagePrint " - Cloud Provider"           "$PCF_DEPLOYMENT_CLOUD"
@@ -77,11 +91,77 @@ else
   messagePrint " - Administrator User"       "$PCF_OPSMANAGER_ADMIN_USER"
   messagePrint " - Administrator Password"   "$PCF_OPSMANAGER_ADMIN_PASS"
 
-  if [ "${PCF_DEPLOY_TILE_PKS_VERSION}" != "" ]; then
-    echo "Pivotal Container Platform (PKS)"
-    messagePrint " - PKS Version"            "$PCF_DEPLOY_TILE_PKS_VERSION"
-    messagePrint " - OM Configuration File"  "$PCF_DEPLOY_TILE_PKS_CONFIG"
-    messagePrint " - Config Description"     "$PCF_DEPLOY_TILE_PKS_DESCRIPTION"
+  if [ "${PCF_TILE_PKS_DEPLOY}" == "true" ]; then
+    if [ "${PCF_TILE_PKS_ADMIN_USER}" == "" -o "${PCF_TILE_PKS_ADMIN_PASS}" == "" -o "${PCF_TILE_PKS_ADMIN_EMAIL}" == "" ]; then
+      missing_variables=1
+      echo ""
+      echo "  MISSING ENVIRONMENT-VARIABES    DESCRIPTION        "
+      echo "  --------------------------------------------------------------------------------------------------------------"
+
+      if [ "${PCF_TILE_PKS_ADMIN_USER}" == "" ]; then
+        echo "  PCF_TILE_PKS_ADMIN_USER       (required) PKS Administrator User"
+      fi
+
+      if [ "${PCF_TILE_PKS_ADMIN_PASS}" == "" ]; then
+        echo "  PCF_TILE_PKS_ADMIN_PASS       (required) PKS Administrator Password"
+      fi
+
+      if [ "${PCF_TILE_PKS_ADMIN_EMAIL}" == "" ]; then
+        echo "  PCF_TILE_PKS_ADMIN_EMAIL      (required) PKS Administrator Email"
+      fi
+    else
+      echo "Pivotal Container Platform (PKS)"
+      messagePrint " - PKS Version"                   "$PCF_TILE_PKS_VERSION"
+      messagePrint " - PKS Product SLUG"              "$PCF_TILE_PKS_SLUG"
+      messagePrint " - OM Configuration File"         "$PCF_TILE_PKS_CONFIG"
+      messagePrint " - Config Description"            "$PCF_TILE_PKS_DESCRIPTION"
+      messagePrint " - PAS Stemcell Type"             "$PCF_TILE_PKS_STEMCELL_TYPE"
+      messagePrint " - PAS Stemcell Version"          "$PCF_TILE_PKS_STEMCELL_VERSION"
+      messagePrint " - PKS Administrator User"        "$PCF_TILE_PKS_ADMIN_USER"
+      messagePrint " - PKS Administrator Password"    "$PCF_TILE_PKS_ADMIN_PASS"
+      messagePrint " - PKS Administrator Email"       "$PCF_TILE_PKS_ADMIN_EMAIL"
+    fi
+  fi
+
+  if [ "${PCF_TILE_PAS_DEPLOY}" == "true" ]; then
+    if [ "${PCF_TILE_PAS_ADMIN_USER}" == "" -o "${PCF_TILE_PAS_ADMIN_PASS}" == "" -o "${PCF_TILE_PAS_ADMIN_EMAIL}" == "" ]; then
+      missing_variables=1
+      echo ""
+      echo "  MISSING ENVIRONMENT-VARIABES    DESCRIPTION        "
+      echo "  --------------------------------------------------------------------------------------------------------------"
+
+      if [ "${PCF_TILE_PAS_ADMIN_USER}" == "" ]; then
+        echo "  PCF_TILE_PAS_ADMIN_USER       (required) CF Administrator User"
+      fi
+
+      if [ "${PCF_TILE_PAS_ADMIN_PASS}" == "" ]; then
+        echo "  PCF_TILE_PAS_ADMIN_PASS       (required) CF Administrator Password"
+      fi
+
+      if [ "${PCF_TILE_PAS_ADMIN_EMAIL}" == "" ]; then
+        echo "  PCF_TILE_PAS_ADMIN_EMAIL      (required) CF Administrator Email"
+      fi
+    else
+      echo "Pivotal Container Platform (PAS)"
+      messagePrint " - PAS Version"                   "$PCF_TILE_PAS_VERSION"
+      messagePrint " - PAS Product SLUG"              "$PCF_TILE_PAS_SLUG"
+      messagePrint " - OM Configuration File"         "$PCF_TILE_PAS_CONFIG"
+      messagePrint " - OM Configuration Description"  "$PCF_TILE_PAS_DESCRIPTION"
+      messagePrint " - PAS Stemcell Type"             "$PCF_TILE_PAS_STEMCELL_TYPE"
+      messagePrint " - PAS Stemcell Version"          "$PCF_TILE_PAS_STEMCELL_VERSION"
+      messagePrint " - PAS Administrator User"        "$PCF_TILE_PAS_ADMIN_USER"
+      messagePrint " - PAS Administrator Password"    "$PCF_TILE_PAS_ADMIN_PASS"
+      messagePrint " - PAS Administrator Email"       "$PCF_TILE_PAS_ADMIN_EMAIL"
+    fi
+  fi
+
+  if [ ${missing_variables} -eq 1 ]; then
+    echo "  --------------------------------------------------------------------------------------------------------------"
+    echo "  IMPORTANT: Please set the missing environment variables either in your shell or in the pcfconfig"
+    echo "             configuration file ~/.pcfconfig and set all variables with the 'export' notation"
+    echo "             ie. => export AZURE_PKS_TLS_CERTIFICATE=/home/demouser/certs/cert.pem"
+    echo "  --------------------------------------------------------------------------------------------------------------"
+    exit 1
   fi
 fi
 
@@ -90,15 +170,17 @@ write_line
 checkCloudCLI
 write_line
 
-# --- CHECK ENVIRONMENT VARIABLES ---
-if [ -f ~/.pcfconfig ]; then 
-  . ~/.pcfconfig
-fi
-
 checkCloudAccess
 installJumpHost jump-${PCF_DEPLOYMENT_ENV_NAME}.${AWS_HOSTED_DNS_DOMAIN}
 
 createENVfile $DEPLOYMENT /tmp/deployPCFenv
+$SCP_COMMAND /tmp/deployPCFenv ${SSH_USER}@${SSH_HOST}:/tmp > /dev/null 2>&1
+
+scripts/deployPCFwrapper.sh $envFile
+
+exit 1
+$SSH_COMMAND -n "~/pcfconfig/pcfconfig.sh $ARGS"
+$SSH_COMMAND -n "tail -n 1000 -f /tmp/pcfconfig.log --pid \$(cat /tmp/pcfconfig.pid)"
 
 
 
