testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -888,7 +888,6 @@ installJumpHost() {
   CERTS_ENDDATE=$($SSH_COMMAND -n "openssl x509 -noout -in ~/pcfconfig/certificates/cert.pem -enddate | awk -F'=' '{ print \$2 }'")
   CERTS_EXPIRED=$($SSH_COMMAND -n "openssl x509 -noout -in ~/pcfconfig/certificates/cert.pem -checkend 3600 > /dev/null 2>&1; echo \$?")
 
-CERTS_EXPIRED=1
   if [ $CERTS_EXPIRED -eq 0 ]; then 
     messagePrint " - Certificate Expiratation Data:" "$CERTS_ENDDATE"
   else
@@ -896,56 +895,48 @@ CERTS_EXPIRED=1
     CERTS_GENERATE_NEW=true
   fi
 
-exit 1
-
-  if [ "${stt}" != "ok" ]; then 
+  if [ "${CERTS_GENERATE_NEW}" == "true" ]; then 
     route53createHostedZone $domain
 
-#iiiiiiiiiiiiiiiiiiii
-    if [ -d $PCFPATH/certificates/$domain -a -f $PCFPATH/certificates/$domain/privkey.pem ]; then 
-      messageTitle "Take local cached certificates for PKS Domains ($domain)"  
-      $SCP_COMMAND $PCFPATH/certificates/$domain/* ${SSH_USER}@${SSH_HOST}:~/pcfconfig/certificates > /dev/null 2>&1
-    else
-      echo "-------------------------------------- GENERATE LET'S-ENCRYPT CERTIFICATES -------------------------------------"
-      typ=$(echo $domain | egrep -c "azpks|awspks|gcppks")
-      if [ $typ -ne 0 ]; then
-        echo "Generate Certificate for PKS Domains ($domain)"  
-        #$SSH_COMMAND -n "echo \"certbot certonly --dns-route53 -d '*.$domain' -d '*.api.$domain' -d '*.apps-cl1.$domain'\"" 
-        $SSH_COMMAND -n "sudo certbot certonly --dns-route53 -d '*.$domain' -d '*.api.$domain' -d 'api.pks.$domain' -d '*.apps-cl1.$domain' \
-                     -d '*.apps-cl2.$domain' -d '*.apps-cl3.$domain' -m sadubois@pivotal.io --agree-tos -n --expand"
-        if [ $? -ne 0 ]; then 
-          echo "ERROR: failed to generate certificate. There are probably to many cert requests happends and a limit reached"
-          echo "       Try it again after some hours or search *.$domain in https://crt.sh/"
-            exit 1
-        fi
-      else
-        echo "Generate Certificate for PAS Domains ($domain)"  
-        $SSH_COMMAND -n "sudo certbot certonly --dns-route53 -d '*.$domain' -d '*.apps.$domain' -d '*.sys.$domain' \
-                     -m sadubois@pivotal.io --agree-tos -n --expand"
-        if [ $? -ne 0 ]; then 
-          echo "ERROR: failed to generate certificate. There are probably to many cert requests happends and a limit reached"
-          echo "       Try it again after some hours or search *.$domain in https://crt.sh/"
+    echo "-------------------------------------- GENERATE LET'S-ENCRYPT CERTIFICATES -------------------------------------"
+    typ=$(echo $domain | egrep -c "azpks|awspks|gcppks")
+    if [ $typ -ne 0 ]; then
+      messageTitle "Generate Certificate for PKS Domains ($domain)"  
+      #$SSH_COMMAND -n "echo \"certbot certonly --dns-route53 -d '*.$domain' -d '*.api.$domain' -d '*.apps-cl1.$domain'\"" 
+      $SSH_COMMAND -n "sudo certbot certonly --dns-route53 -d '*.$domain' -d '*.api.$domain' -d 'api.pks.$domain' -d '*.apps-cl1.$domain' \
+                   -d '*.apps-cl2.$domain' -d '*.apps-cl3.$domain' -m sadubois@pivotal.io --agree-tos -n --expand"
+      if [ $? -ne 0 ]; then 
+        echo "ERROR: failed to generate certificate. There are probably to many cert requests happends and a limit reached"
+        echo "       Try it again after some hours or search *.$domain in https://crt.sh/"
           exit 1
-        fi
       fi
-
-      # --- GET A COPY OF THE CERTIFICATES BACK ---
-      [ ! -d ./certificates/$domain ] && mkdir -p ./certificates/$domain
-
-      $SSH_COMMAND -n "[ -d /etc/letsencrypt/live ] && sudo chmod -R a+r /etc/letsencrypt/live /etc/letsencrypt/archive"
-      $SSH_COMMAND -n "[ -d /etc/letsencrypt/live ] && sudo chmod 777 /etc/letsencrypt/live /etc/letsencrypt/live/$domain"
-      $SSH_COMMAND -n "[ -d /etc/letsencrypt/archive ] && sudo chmod 777 /etc/letsencrypt/archive /etc/letsencrypt/archive/$domain"
-      $SSH_COMMAND -n "[ -d /etc/letsencrypt/live/$domain ] && cp /etc/letsencrypt/live/$domain/* ~/pcfconfig/certificates"
-
-      messageTitle " Copy new certificates from jump to local ./certificates/$domain" 
-      while [ ! -f ./certificates/$domain/fullchain.pem ]; do
-        $SCP_COMMAND ${SSH_USER}@${SSH_HOST}:$SSH_HOME/pcfconfig/certificates/* $PCFPATH/certificates/$domain/ > /dev/null 2>&1
-
-        sleep 10
-      done
-
-      echo "----------------------------------------------------------------------------------------------------------------"
+    else
+      messageTitle "Generate Certificate for PAS Domains ($domain)"  
+      $SSH_COMMAND -n "sudo certbot certonly --dns-route53 -d '*.$domain' -d '*.apps.$domain' -d '*.sys.$domain' \
+                   -m sadubois@pivotal.io --agree-tos -n --expand"
+      if [ $? -ne 0 ]; then 
+        echo "ERROR: failed to generate certificate. There are probably to many cert requests happends and a limit reached"
+        echo "       Try it again after some hours or search *.$domain in https://crt.sh/"
+        exit 1
+      fi
     fi
+
+    # --- GET A COPY OF THE CERTIFICATES BACK ---
+    [ ! -d ./certificates/$domain ] && mkdir -p ./certificates/$domain
+
+    $SSH_COMMAND -n "[ -d /etc/letsencrypt/live ] && sudo chmod -R a+r /etc/letsencrypt/live /etc/letsencrypt/archive"
+    $SSH_COMMAND -n "[ -d /etc/letsencrypt/live ] && sudo chmod 777 /etc/letsencrypt/live /etc/letsencrypt/live/$domain"
+    $SSH_COMMAND -n "[ -d /etc/letsencrypt/archive ] && sudo chmod 777 /etc/letsencrypt/archive /etc/letsencrypt/archive/$domain"
+    $SSH_COMMAND -n "[ -d /etc/letsencrypt/live/$domain ] && cp /etc/letsencrypt/live/$domain/* ~/pcfconfig/certificates"
+
+    messageTitle " Copy new certificates from jump to local ./certificates/$domain" 
+    while [ ! -f ./certificates/$domain/fullchain.pem ]; do
+      $SCP_COMMAND ${SSH_USER}@${SSH_HOST}:$SSH_HOME/pcfconfig/certificates/* $PCFPATH/certificates/$domain/ > /dev/null 2>&1
+
+      sleep 10
+    done
+
+    echo "----------------------------------------------------------------------------------------------------------------"
   fi
 
 echo "functions: debug"; exit 1
