added pbs support

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -3000,7 +3000,7 @@ getProductSlug() {
       pivnetAPI $PCF_PIVNET_TOKEN POST products/$slug/releases/$id/eula_acceptance > /dev/null 2>&1
       break
     else
-      echo "ERROR: Unable to find OpsManager $2 om Pivnet"
+      echo "ERROR: Unable to find '$name' on Pivnet"
       exit 1
     fi
   done
@@ -3053,6 +3053,43 @@ uploadStemCell() {
   messagePrint " - Stemcell File:" "/tmp/$file"
 
   $OM $OM_LOGIN upload-stemcell --stemcell /tmp/$file > /dev/null 2>&1
+}
+
+downloadFromPivnet() {
+  PRODUCT_SLUG=$1
+  PRODUCT_VERSION=$2
+  PRODUCT_NAME=$3
+
+  rec=$(echo "$PRODUCT_VERSION" | awk -F'.' '{ print NF }')
+  if [ $rec -eq 2 ]; then SEARCH_STR="^${PRODUCT_VERSION}.[0-9]*$"; else SEARCH_STR="^${PRODUCT_VERSION}$"; fi
+
+  for id in $(pivnetAPI $PCF_PIVNET_TOKEN GET products/$PRODUCT_SLUG/releases 2>/dev/null | \
+              jq -r ".releases[] | select(.version | scan(\"^$SEARCH_STR\")).id" | head -1); do
+
+    fid=$(pivnetAPI $PCF_PIVNET_TOKEN GET products/$PRODUCT_SLUG/releases/$id 2>/dev/null | \
+         jq -r ".product_files[] | select(.name | scan(\"^$PRODUCT_NAME\")) | select(.file_version | scan(\"$PRODUCT_VERSION\")).id")
+
+    if [ "${fid}" != "" ]; then
+      # --- ACCEPT EULA ---
+      pivnetAPI $PCF_PIVNET_TOKEN POST products/$PRODUCT_SLUG/releases/$id/eula_acceptance > /dev/null 2>&1
+      break
+    else
+      echo "ERROR: Unable to find $PRODUCT_SLUG $2 on Pivnet"
+      exit 1
+    fi
+  done
+
+  file=$(pivnetAPI $PCF_PIVNET_TOKEN GET products/$PRODUCT_SLUG/releases/$id 2>/dev/null | \
+       jq -r ".product_files[] | select(.id | tostring | scan(\"^$fid$\")).aws_object_key" | \
+       awk -F'/' '{ print $NF }')
+
+  if [ ! -f /tmp/$file ]; then
+    messageTitle "Download Product from PIVNET"
+    messagePrint " - Product Slug:" "$PRODUCT_SLUG"
+    messagePrint " - Product FileID:" "$fid"
+    messagePrint " - Download Location:" "/tmp/$file"
+    pivnetAPIdownload $PCF_PIVNET_TOKEN $PRODUCT_SLUG $id $fid $file
+  fi
 }
 
 uploadProductTile() {
