check return value of certbot

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -720,7 +720,7 @@ installJumpHost() {
       $SSH_COMMAND -n "sudo certbot certonly --dns-route53 -d '*.$domain' -d '*.api.$domain' -d '*.apps-cl1.$domain' \
                    -d '*.apps-cl2.$domain' -d '*.apps-cl3.$domain' -m sadubois@pivotal.io --agree-tos -n --expand"
       if [ $? -ne 0 ]; then 
-        echo "ERROR: failed to generate certificate"; exit 1
+        echo "ERROR: failed to generate certificate. Try it again after some hours"; exit 1
       fi
     else
       echo "Generate Certificate for PAS Domains ($domain)"  
