testing

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1185,8 +1185,28 @@ echo gaga14
   fi
 }
 
-cleanAWSenv() {
+cleanAWSlb() {
+  # --- DELETE PKS LOAD-BALANCERS ---
+  for n in elb-api-lb k8s-master-cl1 k8s-master-cl2 k8s-master-cl3; do
+    aws --region $AWS_LOCATION elb describe-load-balancers --load-balancer-names k8s-master-cl2 >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+      for tag in $(aws --region $AWS_LOCATION elb describe-tags --load-balancer-name k8s-master-cl1 2>/dev/null | \
+        jq -r '.TagDescriptions[].Tags[].Value'); do
 
+        if [ "${tag}" == "${ENV_NAME}" ]; then 
+          aws --region $AWS_LOCATION elb delete-load-balancer --load-balancer-name $n >/dev/null 2>&1
+          if [ $? -ne 0 ]; then
+            echo "ERROR: failled to delete load-balancer: $n"
+            echo "aws --region $AWS_LOCATION elb delete-load-balancer --load-balancer-name $n"
+            exit 1
+          fi
+        fi
+      done
+    fi
+  done
+}
+
+cleanAWSenv() {
   # --- DELETE HOSTED ZONE ---
   domain="$ENV_NAME.$AWS_HOSTED_DNS_DOMAIN"
   ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name ${domain} | \
