bug fix

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1647,31 +1647,31 @@ echo "ID:$id"
     sleep 60
 
     # --- DELETE ADDRESSES ---
-    SECGRP=/tmp/$$_aws_routing_table.json
-    aws --region $AWS_LOCATION ec2 describe-addresses > $SECGRP
-    tot=$(grep -c "PublicIp" $SECGRP); i=0; let tot=tot-1
-    while [ $i -le $tot ]; do
-      pid=$(jq -r ".Addresses[$i].PublicIp" 2>/dev/null $SECGRP)
-      aid=$(jq -r ".Addresses[$i].AllocationId" 2>/dev/null $SECGRP)
-
-      cnt=$(jq -r ".Addresses[$i].Tags[].Value" 2>/dev/null $SECGRP | egrep -c "^${ENV_NAME}")
-      if [ $cnt -gt 0 ]; then
-        messagePrint " - Release PublicIP:" "$pid"
-        aws --region $AWS_LOCATION ec2 release-address --allocation-id $aid > /dev/null 2>&1; re1=$?
-        aws --region $AWS_LOCATION ec2 release-address --public-ip $pid > /dev/null 2>&1; re2=$?
-        if [ $re1 -ne 0 -a $re2 -ne 0 ]; then
-#=> Delete NatGateway first (awspks-nat) 1660 llllllll
-          echo "ERROR: 1failed to release IP: $pid"
-          echo "aws --region $AWS_LOCATION ec2 release-address --allocation-id $aid"
-          echo "aws --region $AWS_LOCATION ec2 release-address --public-ip $pid"
-          exit 1
-        fi
-
-        sleep 20
-      fi
-
-      let i=i+1
-    done
+#    SECGRP=/tmp/$$_aws_routing_table.json
+#    aws --region $AWS_LOCATION ec2 describe-addresses > $SECGRP
+#    tot=$(grep -c "PublicIp" $SECGRP); i=0; let tot=tot-1
+#    while [ $i -le $tot ]; do
+#      pid=$(jq -r ".Addresses[$i].PublicIp" 2>/dev/null $SECGRP)
+#      aid=$(jq -r ".Addresses[$i].AllocationId" 2>/dev/null $SECGRP)
+#
+#      cnt=$(jq -r ".Addresses[$i].Tags[].Value" 2>/dev/null $SECGRP | egrep -c "^${ENV_NAME}")
+#      if [ $cnt -gt 0 ]; then
+#        messagePrint " - Release PublicIP:" "$pid"
+#        aws --region $AWS_LOCATION ec2 release-address --allocation-id $aid > /dev/null 2>&1; re1=$?
+#        aws --region $AWS_LOCATION ec2 release-address --public-ip $pid > /dev/null 2>&1; re2=$?
+#        if [ $re1 -ne 0 -a $re2 -ne 0 ]; then
+##=> Delete NatGateway first (awspks-nat) 1660 llllllll
+#          echo "ERROR: 1failed to release IP: $pid"
+#          echo "aws --region $AWS_LOCATION ec2 release-address --allocation-id $aid"
+#          echo "aws --region $AWS_LOCATION ec2 release-address --public-ip $pid"
+#          exit 1
+#        fi
+#
+#        sleep 20
+#      fi
+#
+#      let i=i+1
+#    done
 
     # --- CLEANUP ---
     rm -f $TMPAWS
@@ -1807,6 +1807,9 @@ echo "ID:$id"
 
     let i=i+1
   done
+
+
+echo "LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10"
 
   # --- CLEANUP ---
   rm -f $TMPVCP
