added TLS feature to AWS PAS

diff --git a/pcfconfig-pks-debug b/pcfconfig-pks-debug
--- a/pcfconfig-pks-debug
+++ b/pcfconfig-pks-debug
@@ -105,9 +105,6 @@ while [ "$1" != "" ]; do
   esac
   shift
 done
-echo "hhh TLS_CERTIFICATE:$TLS_CERTIFICATE"
-echo "hhh TLS_PRIVATE_KEY:$TLS_PRIVATE_KEY"
-echo "hhh TLS_ROOT_CERT:$TLS_ROOT_CERT"
 
 [ "$PKS_CLUSTER_1_NAME" == "-" ] && PKS_CLUSTER_1_NAME=""
 [ "$PKS_CLUSTER_1_PLAN" == "-" ] && PKS_CLUSTER_1_PLAN=""
@@ -1871,7 +1868,7 @@ if [ "${PCFCONFIG_BASE}" == "pcfconfig-pks" -o "${PCFCONFIG_BASE}" == "pcfconfig
       TLS_HOST_NAME="*.sys.${DNS_PREFIX}.${DNS_SUFFIX}.,*.apps.${DNS_PREFIX}.${DNS_SUFFIX}.,*.${DNS_SUFFIX}.,${DNS_SUFFIX}.,${DNS_PREFIX}.${DNS_SUFFIX}"
       TLS_HOST_NAME="*.sys.${DNS_PREFIX}.${DNS_SUFFIX},*.apps.${DNS_PREFIX}.${DNS_SUFFIX},*.${DNS_SUFFIX},${DNS_SUFFIX},${DNS_PREFIX}.${DNS_SUFFIX}"
 
-      messagePrint " - Generating Customer TLS Certificate" "${TLS_HOST_NAME}"
+      messagePrint " - Generating Self-Signed TLS Certificate" "${TLS_HOST_NAME}"
 
       TLS_TEMP_CERT=/tmp/$$_cert
       OM_LOGIN="--skip-ssl-validation --target ${OPS_MANAGER_URL} --username admin --password pivotal"
@@ -1883,6 +1880,15 @@ if [ "${PCFCONFIG_BASE}" == "pcfconfig-pks" -o "${PCFCONFIG_BASE}" == "pcfconfig
       TLS_CERTIFICATE=$(jq '.certificate' $TLS_TEMP_CERT)
       TLS_PRIVATE_KEY=$(jq '.key' $TLS_TEMP_CERT)
     else
+      messagePrint " - Verify Customer TLS Certificate for hosts" "${TLS_HOST_NAME}"
+      dif=$((openssl rsa -in $TLS_CERTIFICATE -noout -modulus; openssl x509 -in $TLS_PRIVATE_KEY -noout -modulus) | uniq -c | awk '{ print $1 }')
+      if [ $dif -ne 2 ]; then 
+        echo "ERROR: Certificate modulus of $TLS_CERTIFICATE does not match with the private_key $TLS_PRIVATE_KEY"
+        echo "       => openssl rsa -in $TLS_CERTIFICATE -noout -modulus"
+        echo "       => openssl x509 -in $TLS_PRIVATE_KEY -noout -modulus"
+        exit 1
+      fi
+
 echo "TLS_CERTIFICATE:$TLS_CERTIFICATE"
 echo "TLS_PRIVATE_KEY:$TLS_PRIVATE_KEY"
 echo "TLS_ROOT_CERT:$TLS_ROOT_CERT"
