aws lb fix

diff --git a/pcfconfig-pks b/pcfconfig-pks
--- a/pcfconfig-pks
+++ b/pcfconfig-pks
@@ -3445,24 +3445,25 @@ echo gaga14
 echo "AWS_ID:$AWS_ID"
 echo "AWS_SG:$AWS_SG"
 echo "AWS_VP:$AWS_VP"
-      AWS_SGID=""
-      for sg in $(aws ec2 --region $AWS_REGION describe-security-groups | jq -r '.SecurityGroups[].GroupId'); do
-        aws ec2 --region $AWS_REGION describe-security-groups --group-ids $sg > /tmp/$$_sg
-        des=$(jq -r '.SecurityGroups[].Description' /tmp/$$_sg)
-        nam=$(jq -r '.SecurityGroups[].GroupName' /tmp/$$_sg)
-        cnt=$(echo "${nam}" | egrep -c "\-$AWS_ID") 
-        if [ "${cnt}" -gt 0 ]; then
-          AWS_SG_NEW=$sg
-          aws elb --region $AWS_REGION apply-security-groups-to-load-balancer --load-balancer-name $AWS_LB \
-                  --security-groups $AWS_SG $AWS_SG_NEW > /dev/null 2>&1
-          if [ $? -ne 0 ]; then 
-            echo "ERROR: failed to set SecurityGroup"
-            echo "       => aws elb --region $AWS_REGION apply-security-groups-to-load-balancer \\"
-            echo "                  --load-balancer-name $AWS_LB --security-groups $AWS_SG $AWS_SG_NEW"
-            exit 1
-          fi
-        fi
-      done
+
+#      AWS_SGID=""
+#      for sg in $(aws ec2 --region $AWS_REGION describe-security-groups | jq -r '.SecurityGroups[].GroupId'); do
+#        aws ec2 --region $AWS_REGION describe-security-groups --group-ids $sg > /tmp/$$_sg
+#        des=$(jq -r '.SecurityGroups[].Description' /tmp/$$_sg)
+#        nam=$(jq -r '.SecurityGroups[].GroupName' /tmp/$$_sg)
+#        cnt=$(echo "${nam}" | egrep -c "\-$AWS_ID") 
+#        if [ "${cnt}" -gt 0 ]; then
+#          AWS_SG_NEW=$sg
+#          aws elb --region $AWS_REGION apply-security-groups-to-load-balancer --load-balancer-name $AWS_LB \
+#                  --security-groups $AWS_SG $AWS_SG_NEW > /dev/null 2>&1
+#          if [ $? -ne 0 ]; then 
+#            echo "ERROR: failed to set SecurityGroup"
+#            echo "       => aws elb --region $AWS_REGION apply-security-groups-to-load-balancer \\"
+#            echo "                  --load-balancer-name $AWS_LB --security-groups $AWS_SG $AWS_SG_NEW"
+#            exit 1
+#          fi
+#        fi
+#      done
 
       cnt=$(echo "${AWS_SG}" | egrep -c "$AWS_SG_NEW") 
       if [ $cnt -eq 0 ]; then 
@@ -3480,7 +3481,7 @@ echo "AWS_VP:$AWS_VP"
 
       if [ "${ZONE_ID}" != "" ]; then
         ZONE="*.${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}"
-        ZONE="*.apps.${DNS_PREFIX}.${DNS_SUFFIX}"
+        ZONE="*.apps-${cluster}.${DNS_PREFIX}.${DNS_SUFFIX}"
 
     cat << EOF | sed -e "s/FQHN/${ZONE}/g" -e "s/AAAA/$DNSLB/g" -e "s/ZZID/$DNSLB_ZONEID/g" > /tmp/$$_zone_record
 {
